# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f31be04609dbeeba41f28328e912dea50b3ba5fa1b3362520bca521209df289e8df73b8d05e0ec65de7d89da53aa12e2f5ffd702d6c14acefa545aa3c143e5f1

test:
  secret_key_base: 7bdd8d2446a7b91a7c4022d05cf12791524d857c8b77f1aaaf40cbbfe13291867bca982935928cc4458eeca71277b8035ebc91e27c3561054fe5a3142678eefa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
